language: node_js
node_js: 12
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn generate

deploy:
  provider: firebase
  project: "comments-downloader"
  token: "$FIREBASE_TOKEN"
  skip_cleanup: true
  on:
    branch: master
